server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive" always;

    location / {
        try_files $uri $uri/ =404;
    }
}
